"""added use_rag column in chatbot datas table

Revision ID: 14e48dcda7fc
Revises: e3cb4ea57613
Create Date: 2024-05-20 13:35:44.935520

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14e48dcda7fc"
down_revision = "e3cb4ea57613"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chatbot_datas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("use_rag", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chatbot_datas", schema=None) as batch_op:
        batch_op.drop_column("use_rag")

    # ### end Alembic commands ###
