"""updated response_status in feedback table

Revision ID: 7900af27159d
Revises: 8b2df0e74846
Create Date: 2024-04-01 18:05:52.290226

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7900af27159d"
down_revision = "8b2df0e74846"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["chatbot_datas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("feedback_datas")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_datas",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("exchange_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("feedback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "response_accepted", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "response_declined", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["chatbot_datas.id"],
            name="feedback_datas_exchange_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="feedback_datas_pkey"),
    )
    op.drop_table("feedback")
    # ### end Alembic commands ###
