"""added feedback_model

Revision ID: 8b2df0e74846
Revises: dd36ed33f8b4
Create Date: 2024-03-19 11:24:10.324963

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b2df0e74846"
down_revision = "577c92494589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_datas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("response_accepted", sa.Boolean(), nullable=True),
        sa.Column("response_declined", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["chatbot_datas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("feedback_datas")
    # ### end Alembic commands ###
