"""added role in user model

Revision ID: a537ab3a4917
Revises: 7900af27159d
Create Date: 2024-04-10 12:07:49.834662

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a537ab3a4917"
down_revision = "7900af27159d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response_evaluation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("user_input", sa.Text(), nullable=True),
        sa.Column("final_response", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("faithfulness", sa.Float(), nullable=True),
        sa.Column("answer_relevancy", sa.Float(), nullable=True),
        sa.Column("context_utilization", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["chatbot_datas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    op.drop_table("response_evaluation")
    # ### end Alembic commands ###
