"""added use_rag column in chatdata table to store toggle

Revision ID: b309df781d1f
Revises: e3cb4ea57613
Create Date: 2024-05-16 22:57:41.319998

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b309df781d1f"
down_revision = "e3cb4ea57613"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("chatbot_datas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("use_rag", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chatbot_datas", schema=None) as batch_op:
        batch_op.drop_column("use_rag")
    # ### end Alembic commands ###
