"""set user_input and final_response column to non-nullable

Revision ID: be34ba45e178
Revises: 6337e7411249
Create Date: 2024-04-15 01:54:15.128516

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be34ba45e178"
down_revision = "6337e7411249"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluation_scores", schema=None) as batch_op:
        batch_op.alter_column("user_input", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("final_response", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluation_scores", schema=None) as batch_op:
        batch_op.alter_column("final_response", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("user_input", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
