"""updated_metrics

Revision ID: e3cb4ea57613
Revises: be34ba45e178
Create Date: 2024-05-14 12:25:31.832634

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3cb4ea57613"
down_revision = "be34ba45e178"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatbot_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("exchange_count", sa.Integer(), nullable=True),
        sa.Column("exchange_ids", sa.Text(), nullable=True),
        sa.Column("response_accepted_count", sa.Integer(), nullable=True),
        sa.Column("response_declined_count", sa.Integer(), nullable=True),
        sa.Column("response_time", sa.SmallInteger(), nullable=True),
        sa.Column("exchange_cost", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("time_stamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chatbot_metrics")
    # ### end Alembic commands ###
