name: '[PRN] Quality Engineering'
on:
  pull_request:
    branches:
      - main
      - master
      - dev
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - closed
  push:
    branches:
      - main
      - master
      - dev
jobs:
  quality-engineering:
    name: QE
    uses: bitcot/aiqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      danger: true
      nodeLint: false
      pythonFormat: true
      sonar: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}
      PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      TASK_DEFINITION_BUCKET: ${{secrets.TASK_DEFINITION_BUCKET}}
